- name: Python App Installation
  hosts: app_hosts
  become: true
  vars:
    execution_username: ubuntu
    python_version: python3
    pip_path: /usr/bin/pip3
    virtualenv_path: /usr/local/bin/virtualenv
    code_deployment_path: /opt/apps/gen-ai
    python_requirements_file_name: requirements.txt
    venv_folder_name: .venv
    folder_permission: "0777"
    sh_management_file_name: manage_app.sh
    operation: start
    os_environment:
      - key: OPENAI_API_KEY
        value: "{{ openai_api_key_value }}"
  pre_tasks:
    - name: Update apt-get repo and cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install python pip3
      apt:
        name: python3-pip

    - name: Install virtualenv python package
      pip:
        name: virtualenv
        executable: "{{ pip_path }}"

  tasks:
    - name: Creates code deployment directory
      file:
        path: "{{ code_deployment_path }}"
        state: directory
        mode: "{{ folder_permission }}"
        recurse: yes
        owner: "{{ execution_username }}"
        group: "{{ execution_username }}"

    - name: Add OPENAI_API_KEY environment variable to the bash profile
      lineinfile:
        dest: "/etc/environment"
        state: present
        regexp: "^{{ item.key }}="
        line: "{{ item.key }}={{ item.value }}"
        backup: true
      with_items: "{{ os_environment }}"

    - name: Refresh environment values
      shell: . ~/.bashrc
      args:
        executable: "{{ ansible_shell }}"
      become_user: "{{ execution_username }}"

    - name: Copy code from Jenkins workspace to code deployment directory
      copy:
        dest: "{{ code_deployment_path }}"
        src: "{{ jenkins_workspace_path }}/src/"
        mode: "{{ folder_permission }}"
        owner: "{{ execution_username }}"
        group: "{{ execution_username }}"

    - name: Create Python virtual environment and install app requirements
      venv:
        name: "{{ code_deployment_path }}/{{ venv_folder_name }}"
        python: "{{ python_version }}"
        system_site_packages: no
      become_user: "{{ execution_username }}"

    - name: Install app requirements
      pip:
        requirements: "{{ code_deployment_path }}/{{ python_requirements_file_name }}"
        virtualenv: "{{ code_deployment_path }}/{{ venv_folder_name }}"
        virtualenv_command: "{{ virtualenv_path }}"
      become_user: "{{ execution_username }}"

    - name: Start Python app
      command: "sh {{ sh_management_file_name }} {{ operation }}"
      args:
        chdir: "{{ code_deployment_path }}/"
      become_user: "{{ execution_username }}"
      register: deploy_status

    - name: Print deploy status
      debug: var=deploy_status.stdout
